const cubes = {
  dirt: false,
  grass: false,
  glass: false,
  log: false,
  wood: false,
  cobblestone: false,
  strippedLog: false,
  blackWool: false,
  whiteWool: false,
  blueWool: false,
  brownWool: false,
  cyanWool: false,
  grayWool: false,
  greenWool: false,
  lightBlueWool: false,
  lightGrayWool: false,
  limeWool: false,
  magentaWool: false,
  orangeWool: false,
  pinkWool: false,
  purpleWool: false,
  redWool: false,
  yellowWool: false,
};

export default cubes;
